---
- name: Install apache on Target Nodes
  hosts: webservers
  become: true
  tasks:
  - name: Install apache
    command: yum install httpd
  
  - name: start httpd
    service:
      name: httpd
      state: started
  - name: copy index.html to remote server
    copy:
      src: index.html
      dest: /var/www/html/
   
